# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6

addons:
  code_climate:
    repo_token: 87ffa2288ce3194a10f8d09c8a321af0911f7f8958ccb1a40d5bb8710eb93380

before_script:
  - composer install --dev

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter
